---
version: '3'
services:
  zk1:
    build: ../zookeeper
    container_name: zk1
    ports:
      - '22181:22181'
    volumes:
      - ./data:/usr/local/share/data
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: 'zk1:22888:23888;zk2:32888:33888;zk3:42888:43888'
      KAFKA_JMX_OPTS: '-javaagent:/usr/local/share/jmx_prometheus_javaagent-0.3.0.jar=9404:/usr/local/share/zookeeper-metrics.yml'

  zk2:
    build: ../zookeeper
    container_name: zk2
    ports:
      - '32181:32181'
    volumes:
      - ./data:/usr/local/share/data
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: 'zk1:22888:23888;zk2:32888:33888;zk3:42888:43888'
      KAFKA_JMX_OPTS: '-javaagent:/usr/local/share/jmx_prometheus_javaagent-0.3.0.jar=9404:/usr/local/share/zookeeper-metrics.yml'

  zk3:
    build: ../zookeeper
    container_name: zk3
    ports:
      - '42181:42181'
    volumes:
      - ./data:/usr/local/share/data
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: 'zk1:22888:23888;zk2:32888:33888;zk3:42888:43888'
      KAFKA_JMX_OPTS: '-javaagent:/usr/local/share/jmx_prometheus_javaagent-0.3.0.jar=9404:/usr/local/share/zookeeper-metrics.yml'

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on: [zk1,zk2,zk3]
    ports:
      # On OSX, edit /etc/hosts and add 'kafka' to 127.0.0.1
      # This is because the way broker is advertising and won't listen
      # if the host machine uses 'localhost:9092'. From the host machine
      # Use 'kafka:9092' to bootstrap.
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zk1:22181,zk2:32181,zk3:42181'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'

  cassandra:
    build: ../cassandra
    container_name: cassandra
    ports:
      - '9042:9042'
    volumes:
      - ../db:/var/lib/cassandra

  schema-registry:
    build: ../schema-registry
    container_name: schema-registry
    hostname: schema-registry
    depends_on: [zk1,zk2,zk3,kafka]
    ports:
      - '8081:8081'
    volumes:
      - ./data:/usr/local/share/data
    environment:
      APP_HOST: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zk1:22181,zk2:32181,zk3:42181'
      SCHEMA_REGISTRY_JMX_OPTS: '-javaagent:/usr/local/share/jmx_prometheus_javaagent-0.3.0.jar=9404:/usr/local/share/schema-registry-metrics.yml'

  # Load connector manually
  # docker exec -it connect-1 /usr/local/share/data/setup-connectors
  connect-1:
    build: ../kafka-connect # Because we need the data mounaineer plugin
    container_name: connect-1
    depends_on: [zk1,zk2,zk3,kafka,schema-registry,cassandra]
    ports:
      - '8083:8083'
    volumes:
      - ./data:/usr/local/share/data
    environment:
      APP_HOST: connect-1
      CONNECT_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONNECT_ZOOKEEPER_CONNECT: 'zk1:22181,zk2:32181,zk3:42181'
      CONNECT_GROUP_ID: kafka-connect-group
      CONNECT_PLUGIN_PATH: /usr/local/share/kafka/plugins
      CONNECT_CONFIG_STORAGE_TOPIC: kafka-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: kafka-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: kafka-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      KAFKA_JMX_OPTS: '-javaagent:/usr/local/share/jmx_prometheus_javaagent-0.3.0.jar=9404:/usr/local/share/kafka-connect-metrics.yml'

  # Multiple Kafka REST Proxies will not work properly for consuming
  kafka-rest-1:
    build: ../kafka-rest
    container_name: kafka-rest-1
    depends_on: [zk1,zk2,zk3,kafka,schema-registry]
    ports:
      - '8082:8082'
    volumes:
      - ./data:/usr/local/share/data
    environment:
      APP_HOST: kafka-rest-1
      KAFKA_REST_BOOTSTRAP_SERVERS: 'kafka:9092'
      KAFKA_REST_ZOOKEEPER_CONNECT: 'zk1:22181,zk2:32181,zk3:42181'
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      KAFKA_REST_ID: 'rest-a'
      KAFKA_REST_HOST_NAME: 'kafka-rest-1'
      KAFKAREST_JMX_OPTS: '-javaagent:/usr/local/share/jmx_prometheus_javaagent-0.3.0.jar=9404:/usr/local/share/kafka-rest-metrics.yml'

  prometheus:
    build: .
    container_name: prometheus
    depends_on: [zk1,zk2,zk3,kafka,schema-registry,kafka-rest-1]
    ports:
      - '9090:9090'
    environment:
      PROM_STATIC_CONFIGS: 'kafka-rest#kafka-rest-1:9404|schema-registry#schema-registry:9404|kafka-connect#connect-1:9404|zookeeper#zk1:9404,zk2:9404,zk3:9404'
