global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'kafka-rest'
    static_configs:
      - targets: ['kafka-rest-1:9404']
  - job_name: 'schema-registry'
    static_configs:
      - targets: ['schema-registry:9404']
  - job_name: 'connect-rest'
    static_configs:
      - targets: ['connect-1:9404']
